// <auto-generated />
using System;
using AIPrompt.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIPrompt.Data.Migrations
{
    [DbContext(typeof(AIPromptDbContext))]
    [Migration("20260717143807_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("AIPrompt.Data.Entities.PromptBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FreeText")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TermPhraseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("TermPhraseId");

                    b.ToTable("PromptBlocks");
                });

            modelBuilder.Entity("AIPrompt.Data.Entities.PromptCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PromptCategories");
                });

            modelBuilder.Entity("AIPrompt.Data.Entities.PromptGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PromptGenres");
                });

            modelBuilder.Entity("AIPrompt.Data.Entities.PromptTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("PromptTemplates");
                });

            modelBuilder.Entity("AIPrompt.Data.Entities.RoadmapPhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoadmapProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapProjectId");

                    b.ToTable("RoadmapPhases");
                });

            modelBuilder.Entity("AIPrompt.Data.Entities.RoadmapProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoadmapProjects");
                });

            modelBuilder.Entity("AIPrompt.Data.Entities.RoadmapTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhaseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.ToTable("RoadmapTasks");
                });

            modelBuilder.Entity("AIPrompt.Data.Entities.SavedPrompt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExportFormat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceTemplateId");

                    b.ToTable("SavedPrompts");
                });

            modelBuilder.Entity("AIPrompt.Data.Entities.TermPhrase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GenreId");

                    b.ToTable("TermPhrases");
                });

            modelBuilder.Entity("AIPrompt.Data.Entities.PromptBlock", b =>
                {
                    b.HasOne("AIPrompt.Data.Entities.PromptTemplate", "Template")
                        .WithMany("Blocks")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIPrompt.Data.Entities.TermPhrase", "TermPhrase")
                        .WithMany()
                        .HasForeignKey("TermPhraseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Template");

                    b.Navigation("TermPhrase");
                });

            modelBuilder.Entity("AIPrompt.Data.Entities.PromptTemplate", b =>
                {
                    b.HasOne("AIPrompt.Data.Entities.PromptCategory", "Category")
                        .WithMany("PromptTemplates")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AIPrompt.Data.Entities.RoadmapPhase", b =>
                {
                    b.HasOne("AIPrompt.Data.Entities.RoadmapProject", "RoadmapProject")
                        .WithMany("Phases")
                        .HasForeignKey("RoadmapProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoadmapProject");
                });

            modelBuilder.Entity("AIPrompt.Data.Entities.RoadmapTask", b =>
                {
                    b.HasOne("AIPrompt.Data.Entities.RoadmapPhase", "Phase")
                        .WithMany("Tasks")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phase");
                });

            modelBuilder.Entity("AIPrompt.Data.Entities.SavedPrompt", b =>
                {
                    b.HasOne("AIPrompt.Data.Entities.PromptTemplate", "SourceTemplate")
                        .WithMany()
                        .HasForeignKey("SourceTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SourceTemplate");
                });

            modelBuilder.Entity("AIPrompt.Data.Entities.TermPhrase", b =>
                {
                    b.HasOne("AIPrompt.Data.Entities.PromptCategory", "Category")
                        .WithMany("TermPhrases")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AIPrompt.Data.Entities.PromptGenre", "Genre")
                        .WithMany("TermPhrases")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("AIPrompt.Data.Entities.PromptCategory", b =>
                {
                    b.Navigation("PromptTemplates");

                    b.Navigation("TermPhrases");
                });

            modelBuilder.Entity("AIPrompt.Data.Entities.PromptGenre", b =>
                {
                    b.Navigation("TermPhrases");
                });

            modelBuilder.Entity("AIPrompt.Data.Entities.PromptTemplate", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("AIPrompt.Data.Entities.RoadmapPhase", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("AIPrompt.Data.Entities.RoadmapProject", b =>
                {
                    b.Navigation("Phases");
                });
#pragma warning restore 612, 618
        }
    }
}
